config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'customers#map'

  resources :customers do
    collection do
      get 'map'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord

  # association
  has_many :vehicles, :dependent => :destroy

  accepts_nested_attributes_for :vehicles, allow_destroy: true

  #validations
  validate :validate_properties

  def validate_properties
    if address.blank? or lat.blank? or lng.blank?
      errors.add(:address, "is not valid")
    end
  end

  def self.search(params)
    if (params[:city].present? || params[:state].present? || params[:zip].present?)
      where('lower(city) = ?', params[:city].try(:downcase)).or(where('lower(state) = ?', params[:state].try(:downcase))).or(where('lower(zip) = ?', params[:zip].try(:downcase)))
    else
      all
    end
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  respond_to :html
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
    respond_with @customers
  end

  def new
    @customer = Customer.new
  end

  def create
    # In order to set the flash, we need to know if the create was successful.
    # Since `create` always returns an object we won't know if it's successful,
    # without re-validating or checking the errors.
    #
    # The cleaner way is to just initialize a new object, then check the call
    # to save; which will be truthy on a valid model and successful save.
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = "Customer was successfully created."
    end
    respond_with @customer, location: -> { customers_path }
  end

  def edit
    
  end

  def show
    
  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "Customer was successfully updated."
    end

    respond_with @customer
  end

  def destroy
    flash[:notice] = "Customer was successfully destroyed."
    respond_with @customer.destroy
  end

  def map
    @customers = Customer.search(params)
    @hash = Gmaps4rails.build_markers(@customers) do |customer, marker|
      marker.lat customer.lat
      marker.lng customer.lng
      marker.json({ :id => customer.id })
      marker.infowindow render_to_string(:partial => "/customers/box", :locals => { :object => customer})
    end
    respond_with @customers
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :address, :city, :state, :zip, :email, :phone, :lat, :lng, :vehicles_attributes => [:id, :year, :customer_id, :make, :model, :trim, :style, :vin, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-primary form-management", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/customers/_box.html.erb
<div>
  <h6 class="modal-title"><%= object.name %></h6>
</div>
<div>
  <small><b>Address:</b> <%= object.address%></small></br>
  
</div>
<% if object.vehicles.present? %>
  <div class="table-responsive">
    <table id="mytable" class="table table-bordred table-striped">        
      <thead>
        <th>Year</th>
        <th>Make</th>
        <th>Model</th>
        <th>Trim</th>
        <th>Style</th>
        <th>Vin</th>
      </thead>
      <tbody>
        <% object.vehicles.each do |vehicle| %>
          <tr>
            <td><%= vehicle.year %></td>
            <td><%= vehicle.make %></td>
            <td><%= vehicle.model %></td>
            <td><%= vehicle.trim %></td>
            <td><%= vehicle.style %></td>
            <td><%= vehicle.vin %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end%>

app/views/customers/_form.html.erb
<div class="container">
  <div class="col-md-5 col-md-offset-3">
    <div class="well">
    <div class="form-area"> 
      <%= form_for @customer do |f| %>
        <br style="clear:both">
        <h3 style="margin-bottom: 25px; text-align: center;">Customer Form</h3>
        <% if @customer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

            <ul>
            <% @customer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
        </div>
        <div class="form-group">
          <%= f.text_field :address, class: 'form-control', placeholder: 'Address', id: 'geo-input' %>
        </div>
        <%= f.hidden_field :lat %>
        <%= f.hidden_field :lng %>
        <div class="form-group">
          <%= f.text_field :city, class: 'form-control', placeholder: 'City', id: 'locality' %>
        </div>
        <div class="form-group">
          <%= f.text_field :state, class: 'form-control', placeholder: 'State', id: 'administrative_area_level_1' %>
        </div>
        <div class="form-group">
          <%= f.text_field :zip, class: 'form-control', placeholder: 'Zip', id: 'postal_code'  %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        <div class="form-group">
          <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone' %>
        </div>
        
        <div>
          <div id="addresses">
            <%= f.fields_for :vehicles do |vehicle| %>
              <%= render 'vehicle_fields', f: vehicle %>
            <% end %>
            <div class="links">
              <%= link_to_add_fields 'add vehicles', f, :vehicles %>
              <%= f.submit class: 'btn btn-primary pull-right' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/_vehicle_fields.html.erb
<div class="col-md-offset-3">
  <div class="nested-fields">
    <b>Vehicle Detail</b>
    <div class="form-group">
      <%= f.text_field :year, class: 'form-control', placeholder: 'Year' %>
    </div>
    <div class="form-group">
      <%= f.text_field :make, class: 'form-control datepicker', placeholder: 'Make' %>
    </div>
    <div class="form-group">
      <%= f.text_field :model, class: 'form-control', placeholder: 'Model No.' %>
    </div>
    <div class="form-group">
      <%= f.text_field :trim, class: 'form-control', placeholder: 'Trim' %>
    </div>
    <div class="form-group">
      <%= f.text_field :vin, class: 'form-control', placeholder: 'Vin' %>
    </div>
    <div class="form-group">
      <%= f.text_field :style, class: 'form-control', placeholder: 'Style' %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :_destroy %>
      <%= link_to 'remove', '#', class: "remove_fields btn btn-danger" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('.datepicker').datepicker({
      dateFormat: "yy-mm-dd"
    });
  });
</script>

app/views/customers/edit.html.erb
<%= render 'form' %>

app/views/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table id="mytable" class="table table-bordred table-striped">        
          <thead>
            <th></th>
            <th>Name</th>
            <th>Address</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Action</th>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td><span class="glyphicon glyphicon-eye-open <%=  'show-detail' if customer.vehicles.present? %>"></span></td>
                <td><%= customer.name %></td>
                <td><%= customer.address %></td>
                <td><%= customer.email %></td>
                <td><%= customer.phone %></td>
                <td><%= link_to '', edit_customer_path(customer), class: "glyphicon glyphicon-pencil"  %> | <%= link_to '', customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %></td>
              </tr>
              <%if customer.vehicles.present?%>
                <tr style="display: none;">
                  <td colspan=8 bgcolor=" #ede6c2" >
                    <table class="table table-bordred" >
                    <h4>Vehicle List</h4>
                    <thead>
                      <th></th>
                      <th>Year:</th>
                      <th>Make:</th>
                      <th>Model:</th>
                      <th>Trim:</th>
                      <th>Style:</th>
                      <th>Vin:</th>
          
                    </thead>

                      <% customer.vehicles.each do |vehicle| %>
                        <tr>
                          <td></td>
                          <td><%= vehicle.year %></td>
                          <td><%= vehicle.make %></td>
                          <td><%= vehicle.model %></td>
                          <td><%= vehicle.trim %></td>
                          <td><%= vehicle.style %></td>
                          <td><%= vehicle.vin %></td>
                        </tr>
                      <% end %>
                    </table>
                  </td>
                </tr>
              <%end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div>
        <span><%= link_to "Add New Cstomer", new_customer_path, :id => "open-contacts-dialog-btn",
        :class => "btn btn-primary", :method => :get %></span>
        <span><%= link_to "Map", root_path, :class => "btn btn-primary", target: :_blank %></span>
        
      </div>
    </div>
  </div>
</div>

app/views/customers/map.html.erb
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>


<%= form_tag root_path,  :class => 'form-horizontal',:method => "get" do %>
    
    <div class="form-group">
        <div class="col-sm-2">
            <%= text_field_tag :city, '', class: 'form-control', placeholder: 'City', value: params[:city]%>
        </div>
        <div class="col-sm-2">
            <%= text_field_tag :state, '', class: 'form-control', placeholder: 'State', value: params[:state]%>
        </div>
        <div class="col-sm-2">
            <%= text_field_tag :zip, '', class: 'form-control', placeholder: 'Zip', value: params[:zip]%>
        </div>
        <div class="col-sm-2 col-sm-offset-1">
            <%= submit_tag 'Search', class: "btn btn-primary" %>
        </div>
        <%= link_to 'Customer List', customers_path %>
    </div>
<% end %>
<div style='width: 800px;'>
  <div id="map" style='width: 1200px; height: 600px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      disableDefaultUI: true
      // pass in other Google Maps API options here
    },
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = <%= raw @hash.to_json %>
    Gmaps.store = {}
    Gmaps.store.markers = markers.map(function(m) {
      marker = handler.addMarker(m);
      marker.serviceObject.set('id', m.id); // You can add other attributes using set
      return marker;
    });
    handler.bounds.extendWith(Gmaps.store.markers);
    handler.fitMapToBounds();
  }
  );
</script>

app/views/customers/new.html.erb
<%= render 'form' %>

app/views/customers/show.html.erb
<div class="col-sm-12">
<p id="notice"></p>
<table class="table table-bordered table-dark">
  <tr><th>Name:</th>
    <th>Address:</th>
    <th>Email:</th>
    <th>Phone:</th>
  </tr>
  <tr>
    <td><%= @customer.name %></td>
    <td><%= @customer.address %></td>
    <td><%= @customer.email%></td>
    <td><%= @customer.phone%></td>
  </tr>
  <%= link_to 'Back', customers_path %>
</table>
</div>

app/views/layouts/_header.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">ddd</span>
            </li>
            
             
    </ul>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vehicles</title>
    <%= csrf_meta_tags %>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC2sGW-rmeKX3_QMhsGrkrA7ROu7IdaeWU&amp;libraries=places"></script>
    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag "application" %>
  </head>

  <body <%= 'style=background-color:skyblue' if params[:action] == "map" %>
    <div class="container">
        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>